React Calculator milestone 4: Operate and Calculate Logic
t-yanick/react-calculator pull request #4
Opened 2021-05-02 08:13 UTC by t-yanick

In this PR we:
- Implemented the Calculate.js module in which 
* we created a Calculate method which accepts data object and buttonName as arguements
* the method uses the buttonName argument to mutate the calculator’s data object and return its modified version

- Implemented the Operate.js module in which
* the module implemented one named function `operate` which accepts 3 arguments (two numbers and an operation)
* the operation argument performs a simple math operation.
* Operate.js is used in the Calculate module when the buttonName is an operation.

2021-05-02 08:30 UTC, t-yanick commented
The eslint error is coming from the fact that there is no extension in

> import Operate from './Operate';

Even when I put an extension I still get an error on the unexpected use of an extension. I cannot figure out how to fix this issue. I am going to submit for code review with this error and hopefully I can get help from the reviewer. Thanks

2021-05-02 20:31 UTC, krys2fa requested changes
# Status: Marked as Invalid! ⚠️  
Please note that your Code Review Request is being marked as invalid. 
This is because the configs in .github/workflows/ must be exactly the same as that in the [Microverse linter config repo](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml). This is most likely the reason GitHub Actions is throwing errors as well.

💡 Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.
If you think that the change is necessary - open a [Pull Request in this repository](https://github.com/microverseinc/linters-config/blob/master/README.md#contributing).


This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

2021-05-03 06:34 UTC, mikenath223 requested changes
### Hello @t-yanick 👋

**You've done pretty well here, good use of switch statements, and clean modular conditional statements also. 👌**

However, let's make a couple of changes.

- [x] OPTIONAL - Kindly consider removing the table of contents section in the readme, as GitHub automatically now adds a table of content in readme docs.

- Please refer to the comment on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-03 06:36 UTC, mikenath223 commented on src/logic/operate.js
> +  }
- [ ] Since the percentage operator(%) has already been handled correctly in calculate.js, please remove this conditional case here.

2021-05-03 07:09 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-03 07:12 UTC, merged